### ISSUE TITLE
[Bug]: two navbars on top of each other

### ISSUE THREAD

**Issue by Sorinaki** [SamSprung/SamSprung-TooUI#203]
### Issue Description

The bar appears twice

### Logcat Output

```shell
SamSprung - #cb945cb
Android S (12)
Installed by google
Secure Lock Screen

--------- beginning of crash
08-17 07:34:29.009 12696 14481 E AndroidRuntime: FATAL EXCEPTION: pool-131-thread-1
08-17 07:34:29.009 12696 14481 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 12696
08-17 07:34:29.009 12696 14481 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{f2fbc4a} (ac4ef086-f856-4e09-838b-0a82d0309b2e) not attached to an activity.
08-17 07:34:29.009 12696 14481 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:2)
08-17 07:34:29.009 12696 14481 E AndroidRuntime: 	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:4)
08-17 07:34:29.009 12696 14481 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-17 07:34:29.009 12696 14481 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-17 07:34:29.009 12696 14481 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
08-17 07:36:44.133 12696 16048 E AndroidRuntime: FATAL EXCEPTION: pool-242-thread-1
08-17 07:36:44.133 12696 16048 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 12696
08-17 07:36:44.133 12696 16048 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{1d0657a} (3913532b-c86e-47de-9961-9c59718cd713) not attached to an activity.
08-17 07:36:44.133 12696 16048 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:2)
08-17 07:36:44.133 12696 16048 E AndroidRuntime: 	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:4)
08-17 07:36:44.133 12696 16048 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-17 07:36:44.133 12696 16048 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-17 07:36:44.133 12696 16048 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
08-17 12:54:52.176 12696 17058 E AndroidRuntime: FATAL EXCEPTION: pool-545-thread-1
08-17 12:54:52.176 12696 17058 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 12696
08-17 12:54:52.176 12696 17058 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{e2b60a8} (4854298c-54e0-4abf-90e6-f1bb7dd2627f) not attached to an activity.
08-17 12:54:52.176 12696 17058 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:2)
08-17 12:54:52.176 12696 17058 E AndroidRuntime: 	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:4)
08-17 12:54:52.176 12696 17058 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-17 12:54:52.176 12696 17058 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-17 12:54:52.176 12696 17058 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
08-19 12:08:42.941 16879  4402 E AndroidRuntime: FATAL EXCEPTION: pool-403-thread-1
08-19 12:08:42.941 16879  4402 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 16879
08-19 12:08:42.941 16879  4402 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{88a9f55} (15eb5865-f210-4392-a157-fa033e3a6938) not attached to an activity.
08-19 12:08:42.941 16879  4402 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:2)
08-19 12:08:42.941 16879  4402 E AndroidRuntime: 	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:4)
08-19 12:08:42.941 16879  4402 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 12:08:42.941 16879  4402 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 12:08:42.941 16879  4402 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
08-19 12:10:12.860 16879  6417 E AndroidRuntime: FATAL EXCEPTION: pool-553-thread-1
08-19 12:10:12.860 16879  6417 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 16879
08-19 12:10:12.860 16879  6417 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{e68802e} (9f93490e-0781-4309-afa8-0c09931f0f45) not attached to an activity.
08-19 12:10:12.860 16879  6417 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:2)
08-19 12:10:12.860 16879  6417 E AndroidRuntime: 	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:4)
08-19 12:10:12.860 16879  6417 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 12:10:12.860 16879  6417 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 12:10:12.860 16879  6417 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
08-19 12:10:27.881 16879  6839 E AndroidRuntime: FATAL EXCEPTION: pool-586-thread-1
08-19 12:10:27.881 16879  6839 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 16879
08-19 12:10:27.881 16879  6839 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{8d4f7bc} (f5e678e8-8860-4b8e-934a-d7ec0c003ec1) not attached to an activity.
08-19 12:10:27.881 16879  6839 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:2)
08-19 12:10:27.881 16879  6839 E AndroidRuntime: 	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:4)
08-19 12:10:27.881 16879  6839 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 12:10:27.881 16879  6839 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 12:10:27.881 16879  6839 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
08-19 12:11:06.245 16879  7390 E AndroidRuntime: FATAL EXCEPTION: pool-619-thread-1
08-19 12:11:06.245 16879  7390 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 16879
08-19 12:11:06.245 16879  7390 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{a881b} (fad11b33-1701-47d2-92f0-f5a627f6f3f7) not attached to an activity.
08-19 12:11:06.245 16879  7390 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:2)
08-19 12:11:06.245 16879  7390 E AndroidRuntime: 	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:4)
08-19 12:11:06.245 16879  7390 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 12:11:06.245 16879  7390 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 12:11:06.245 16879  7390 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
08-19 12:28:43.491 18174 20060 E AndroidRuntime: FATAL EXCEPTION: pool-139-thread-1
08-19 12:28:43.491 18174 20060 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 18174
08-19 12:28:43.491 18174 20060 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{91580fe} (13178e40-bc82-43a2-bbcb-3fddeb711199) not attached to an activity.
08-19 12:28:43.491 18174 20060 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:2)
08-19 12:28:43.491 18174 20060 E AndroidRuntime: 	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:4)
08-19 12:28:43.491 18174 20060 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 12:28:43.491 18174 20060 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 12:28:43.491 18174 20060 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
--------- beginning of system
08-19 12:29:13.903 18174 18174 E ActivityThread: Service com.eightbit.samsprung.launcher.AppDisplayListener has leaked IntentReceiver com.eightbit.samsprung.launcher.AppDisplayListener$onStartCommand$1@ab8a313 that was originally registered here. Are you missing a call to unregisterReceiver()?
08-19 12:29:13.903 18174 18174 E ActivityThread: android.app.IntentReceiverLeaked: Service com.eightbit.samsprung.launcher.AppDisplayListener has leaked IntentReceiver com.eightbit.samsprung.launcher.AppDisplayListener$onStartCommand$1@ab8a313 that was originally registered here. Are you missing a call to unregisterReceiver()?
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1875)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1594)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1827)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1781)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:743)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at com.eightbit.samsprung.launcher.AppDisplayListener.onStartCommand(AppDisplayListener.kt:11)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.app.ActivityThread.access$2100(ActivityThread.java:310)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.os.Looper.loopOnce(Looper.java:226)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.os.Looper.loop(Looper.java:313)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:8669)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-19 12:29:13.903 18174 18174 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
--------- beginning of main
08-19 12:29:22.149 18174 18174 I DecorView: [INFO] isPopOver=false, config=true
08-19 12:29:22.149 18174 18174 I DecorView: updateCaptionType >> DecorView@827c3d9[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
08-19 12:29:22.149 18174 18174 D DecorView: setCaptionType = 0, this = DecorView@827c3d9[]
08-19 12:29:22.150 18174 18174 I DecorView: getCurrentDensityDpi: from real metrics. densityDpi=480 msg=resources_loaded
08-19 12:29:22.155 18174 18174 D ScrollView: initGoToTop
08-19 12:29:22.208 18174 19183 D OpenGLRenderer: setSurface called with nullptr
08-19 12:29:22.208 18174 18183 D InputTransport: Input channel destroyed: 'ClientS', fd=192
08-19 12:29:22.208 18174 19183 D OpenGLRenderer: setSurface called with nullptr
08-19 12:29:22.208 18174 19183 D OpenGLRenderer: setSurface called with nullptr
08-19 12:29:22.208 18174 19183 D OpenGLRenderer: setSurface called with nullptr
08-19 12:29:22.208 18174 19183 D OpenGLRenderer: setSurface called with nullptr
08-19 12:29:22.210 18174 19183 D OpenGLRenderer: setSurface called with nullptr
08-19 12:29:22.210 18174 19183 D OpenGLRenderer: setSurface called with nullptr
08-19 12:29:22.307 18174 19183 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
08-19 12:29:22.307 18174 18174 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
08-19 12:29:22.310 18174 18174 I ViewRootImpl@8450de7[CoverPreferences]: setView = com.android.internal.policy.DecorView@827c3d9 TM=true
08-19 12:29:22.314 18174 18174 D skia    : --- Failed to create image decoder with message 'unimplemented'
08-19 12:29:22.315 18174 18174 D WallpaperManager: peekWallpaperBitmap: which =1, useCache = true
08-19 12:29:22.315 18174 18174 D WallpaperManager: peekWallpaperBitmap() cached image height=512 width=1006
08-19 12:29:22.316 18174 18174 I PlayCore: UID: [10400]  PID: [18174] AppUpdateService : requestUpdateInfo(com.eightbit.samsprung)
08-19 12:29:22.316 18174 19278 I PlayCore: UID: [10400]  PID: [18174] AppUpdateService : Initiate binding to the service.
08-19 12:29:22.332 18174 20669 D ApplicationPackageManager: we has com.samsung.android.calendar class. reuse it 
08-19 12:29:22.333 18174 20669 I LiveIconLoader: [Calendar] LiveIcon - stdIconSize : 144 , targetIconSize : 144
08-19 12:29:22.333 18174 20669 W LiveIconLoader: System font not found, reverting to Roboto.
08-19 12:29:22.334 18174 20669 I LiveIconLoader: [Calendar] getLiveIcon - Date: 19
08-19 12:29:22.338 18174 18174 I ViewRootImpl@8450de7[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=9 res=0x7 s={true 485331585760} ch=true fn=-1
08-19 12:29:22.338 18174 19183 D OpenGLRenderer: eglCreateWindowSurface
08-19 12:29:22.339 18174 18174 D ScrollView:  onsize change changed 
08-19 12:29:22.339 18174 18174 I ViewRootImpl@8450de7[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11420 android.view.ViewRootImpl.performTraversals:4193 android.view.ViewRootImpl.doTraversal:2919 
08-19 12:29:22.342 18174 18174 D ViewRootImpl@8450de7[CoverPreferences]: Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
08-19 12:29:22.342 18174 18174 D ViewRootImpl@8450de7[CoverPreferences]: Creating frameCompleteCallback
08-19 12:29:22.348 18174 19285 D ViewRootImpl@8450de7[CoverPreferences]: Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
08-19 12:29:22.355 18174 19183 I BufferQueueProducer: [ViewRootImpl@8450de7[CoverPreferences]#12(BLAST Consumer)12](id:46fe0000000c,api:1,p:18174,c:18174) queueBuffer: queued for the first time.
08-19 12:29:22.356 18174 19183 D OpenGLRenderer: GPIS:: SetUp Pid : 18174    Tid : 19183
08-19 12:29:22.356 18174 19183 D ViewRootImpl@8450de7[CoverPreferences]: Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
08-19 12:29:22.357 18174 18174 I ViewRootImpl@8450de7[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4995 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
08-19 12:29:22.357 18174 18174 I ViewRootImpl@8450de7[CoverPreferences]: [DP] rdf()
08-19 12:29:22.357 18174 18174 D ViewRootImpl@8450de7[CoverPreferences]: reportDrawFinished (fn: -1) 
08-19 12:29:22.359 18174 18174 I PlayCore: UID: [10400]  PID: [18174] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
08-19 12:29:22.360 18174 19278 I PlayCore: UID: [10400]  PID: [18174] AppUpdateService : linkToDeath
08-19 12:29:22.367 18174 18174 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.eightbit.samsprung/com.eightbit.samsprung.settings.CoverPreferences
08-19 12:29:22.367 18174 18174 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_STATUS_BAR on com.eightbit.samsprung/com.eightbit.samsprung.settings.CoverPreferences
08-19 12:29:22.374 18174 20547 I PlayCore: UID: [10400]  PID: [18174] OnRequestInstallCallback : onRequestInfo
08-19 12:29:22.374 18174 19278 I PlayCore: UID: [10400]  PID: [18174] AppUpdateService : Unbind from service.
08-19 12:29:22.382 18174 18174 I ViewRootImpl@8450de7[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
08-19 12:29:22.385 18174 18174 D InputMethodManager: startInputInner - Id : 0
08-19 12:29:22.385 18174 18174 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
08-19 12:29:23.189 18174 18174 I ViewRootImpl@8450de7[CoverPreferences]: ViewPostIme pointer 0
08-19 12:29:23.228 18174 18174 I ViewRootImpl@8450de7[CoverPreferences]: ViewPostIme pointer 1
```

### Wiki Confirmation

- [X] I have read the wiki and included a valid log

**Comment by AbandonedCart** [comment]
Closing this as stale
