### ISSUE TITLE
[Bug]: keyboard issue

### ISSUE THREAD

**Issue by DeGusJacoby** [SamSprung/SamSprung-TooUI#91]
### Issue Description

Brother, the keyboard have so many issue and i stop using it but i will not ask for refund. But samsprung tool getting perfect every update. 
Hope next update will bring rotation screen. I oftenly use "My Wuling+" its app for my car so i can control my car like start the engine and unlock the car. Hope u can perfect it your samsprung ui with the app. And i will give more donation to you if u done it
Thanks for the app, great dev
God bless you

### Wiki Confirmation

- [X] I have read and understood the current wiki

**Comment by AbandonedCart** [comment]
It appears the issue with My WULING+ is on their end

```
03-09 06:49:58.896 26856 26856 E AndroidRuntime: FATAL EXCEPTION: main
03-09 06:49:58.896 26856 26856 E AndroidRuntime: Process: com.yonyou.cip.sgmw, PID: 26856
03-09 06:49:58.896 26856 26856 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
03-09 06:49:58.896 26856 26856 E AndroidRuntime: 	at com.blankj.utilcode.util.ToastUtils$1.run(ToastUtils.java:254)
03-09 06:49:58.896 26856 26856 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-09 06:49:58.896 26856 26856 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-09 06:49:58.896 26856 26856 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
03-09 06:49:58.896 26856 26856 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
03-09 06:49:58.896 26856 26856 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8633)
03-09 06:49:58.896 26856 26856 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-09 06:49:58.896 26856 26856 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
03-09 06:49:58.896 26856 26856 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
03-09 06:49:58.897  1285  2294 D SemNscXgbL1: L2 NRT 1 sample inference time: 2.330573 msecs
03-09 06:49:58.899  1285  2294 D SemNscXgbL2Rt: L2 RT 1 sample inference time: 1.683906 msecs
03-09 06:49:58.899 26856 26856 D MyWuling-CrashHandler: BOARD : lahaina
03-09 06:49:58.899 26856 26856 D MyWuling-CrashHandler: BOOTLOADER : F711U1UEU2BVA9
03-09 06:49:58.899 26856 26856 D MyWuling-CrashHandler: BRAND : samsung
03-09 06:49:58.899 26856 26856 D MyWuling-CrashHandler: CPU_ABI : arm64-v8a
03-09 06:49:58.899 26856 26856 D MyWuling-CrashHandler: CPU_ABI2 : 
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: DEVICE : b2q
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: DISPLAY : SP1A.210812.016.F711U1UEU2BVA9
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: FINGERPRINT : samsung/b2quew/b2q:12/SP1A.210812.016/F711U1UEU2BVA9:user/release-keys
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: HARDWARE : qcom
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: HOST : 21DJ6603
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: HW_TIMEOUT_MULTIPLIER : 1
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: ID : SP1A.210812.016
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: IS_CONTAINER : false
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: IS_DEBUGGABLE : false
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: IS_EMULATOR : false
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: IS_ENG : false
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: IS_TREBLE_ENABLED : true
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: IS_USER : true
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: IS_USERDEBUG : false
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: MANUFACTURER : samsung
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: MODEL : SM-F711U1
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: ODM_SKU : unknown
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: PERMISSIONS_REVIEW_REQUIRED : true
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: PRODUCT : b2quew
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: RADIO : unknown
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: SERIAL : unknown
03-09 06:49:58.900 26856 26856 D MyWuling-CrashHandler: SKU : unknown
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: SOC_MANUFACTURER : QTI
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: SOC_MODEL : SM8350
03-09 06:49:58.901  1285  2294 D SemNscXgbL2Nrt: L2 NRT 1 sample inference time: 1.472448 msecs
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: SUPPORTED_32_BIT_ABIS : [Ljava.lang.String;@1413fc3
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: SUPPORTED_64_BIT_ABIS : [Ljava.lang.String;@e07c040
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: SUPPORTED_ABIS : [Ljava.lang.String;@7608b79
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: TAG : Build
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: TAGS : release-keys
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: TIME : 1642157277000
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: TYPE : user
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: UNKNOWN : unknown
03-09 06:49:58.901 26856 26856 D MyWuling-CrashHandler: USER : dpi
03-09 06:49:58.904 26856 27760 V Toast   : show: caller = com.yonyou.cip.sgmw.app.handle.CrashHandler$1.run:135 
03-09 06:49:58.904 26856 27760 V Toast   : show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
03-09 06:49:58.904 26856 27760 V Toast   : show: isActivityContext = false
03-09 06:49:58.907 26856 26856 D CrashHandler:  
03-09 06:49:58.907 26856 26856 D CrashHandler: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
03-09 06:49:58.907 26856 26856 D CrashHandler: │ main, com.yonyou.cip.sgmw.app.handle.CrashHandler.saveCrashInfo2File(CrashHandler.java:264)
03-09 06:49:58.907 26856 26856 D CrashHandler: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
03-09 06:49:58.907 26856 26856 D CrashHandler: │ crash log directory create success
03-09 06:49:58.907 26856 26856 D CrashHandler: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
03-09 06:49:58.907 26856 26856 D CrashHandler:  
03-09 06:49:58.907 26856 26856 D CrashHandler: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
03-09 06:49:58.907 26856 26856 D CrashHandler: │ main, com.yonyou.cip.sgmw.app.handle.CrashHandler.newCrashFile(CrashHandler.java:285)
03-09 06:49:58.907 26856 26856 D CrashHandler: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
03-09 06:49:58.907 26856 26856 D CrashHandler: │ crash log file create success
03-09 06:49:58.907 26856 26856 D CrashHandler: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
